[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"