[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"